source "http://rubygems.org"

gem "activesupport"
gem "awesome_print"
gem "eventmachine"
gem "i18n"
gem "launchy"
gem "mechanize"
gem "notify"
gem "oauth"
gem "slop"
gem "twitter-stream"
gem "twitter_oauth"
